[project]
name = "simple-transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.1.1",
    "ffmpeg-python>=0.2.0",
    "hf-xet>=1.1.2",
]

[dependency-groups]
dev = [
    "watchfiles>=1.0.5",
]
